/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniencuesta;

import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author julia
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        JRBwin = new javax.swing.JRadioButton();
        JRBlinux = new javax.swing.JRadioButton();
        JRBmac = new javax.swing.JRadioButton();
        JCBprogra = new javax.swing.JCheckBox();
        JCBdiseño = new javax.swing.JCheckBox();
        JCBadmin = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        JShoras = new javax.swing.JSlider();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LBLslidder = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(JRBwin);
        JRBwin.setText("Windows");

        buttonGroup1.add(JRBlinux);
        JRBlinux.setText("Linux");

        buttonGroup1.add(JRBmac);
        JRBmac.setText("Mac");

        JCBprogra.setText("Programacion");
        JCBprogra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBprograActionPerformed(evt);
            }
        });

        JCBdiseño.setText("Diseño Grafico");
        JCBdiseño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBdiseñoActionPerformed(evt);
            }
        });

        JCBadmin.setText("Administracion");

        JShoras.setMaximum(10);
        JShoras.setMinorTickSpacing(1);
        JShoras.setSnapToTicks(true);

        jLabel1.setText("Elije tu especialidad");

        jLabel2.setText("Elije un sistema operativo");

        jLabel3.setText("Horas que dedicas en el ordenador");

        LBLslidder.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LBLslidder.setText("0");

        jButton1.setText("Generar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(LBLslidder, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JShoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JCBadmin)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(JRBwin)
                                .addComponent(JRBlinux, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JRBmac, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(JCBprogra)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JCBdiseño, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addGap(17, 17, 17)
                .addComponent(JRBwin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JRBlinux)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JRBmac)
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JCBprogra)
                .addGap(18, 18, 18)
                .addComponent(JCBdiseño)
                .addGap(18, 18, 18)
                .addComponent(JCBadmin)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JShoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBLslidder))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JCBdiseñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBdiseñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBdiseñoActionPerformed

    private void JCBprograActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBprograActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBprograActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String admin="";
        String diseno="";
        String progra="";
          String sisOP="";
          String esp1="",esp2="",esp3="";
          
          
          
          
        if (JRBlinux.isSelected()) {
            sisOP = JRBlinux.getText();
        }
         if (JRBmac.isSelected()) {
             sisOP = JRBmac.getText();
        }
          if (JRBwin.isSelected()) {
             sisOP = JRBwin.getText();
        }
   
          if (JCBadmin.isSelected()) {
            esp1= JCBadmin.getText();
        }
          if (JCBdiseño.isSelected()) {
            esp2= JCBdiseño.getText();
        }

          if (JCBprogra.isSelected()) {
            esp3= JCBprogra.getText();
        }

         
          
        int horas = JShoras.getValue();
       String Shoras=String.valueOf(horas);
        LBLslidder.setText(Shoras);
        if (JCBdiseño.isSelected()) {
            diseno=  JCBdiseño.getText();
        }
        
      JOptionPane.showMessageDialog(null,"Tu sistema operativo preferido es: "+ sisOP+" tus especialidad son: " +esp1+"  " +esp2+ "  "+ esp3 +" y el numero de horas dedicadas al ordenador son:" +horas);

      





        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox JCBadmin;
    private javax.swing.JCheckBox JCBdiseño;
    private javax.swing.JCheckBox JCBprogra;
    private javax.swing.JRadioButton JRBlinux;
    private javax.swing.JRadioButton JRBmac;
    private javax.swing.JRadioButton JRBwin;
    private javax.swing.JSlider JShoras;
    private javax.swing.JLabel LBLslidder;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
