/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imitador;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;



/**
 *
 * @author julia
 */
public class Vimitador extends JFrame implements ActionListener {

  
    public Vimitador() {
        
        initComponents(); 
        
        JC1.addActionListener(this);
        JC2.addActionListener(this);
        JC3.addActionListener(this);  
        JR1.addActionListener(this);
        JR2.addActionListener(this);
        JR3.addActionListener(this);
        JT1.addActionListener(this);
        JCB1.addActionListener(this);

      
    }
   
   
    
    @Override
    public void actionPerformed(ActionEvent e) {
          
    }
    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        JR1 = new javax.swing.JRadioButton();
        JR2 = new javax.swing.JRadioButton();
        JR3 = new javax.swing.JRadioButton();
        JC1 = new javax.swing.JCheckBox();
        JC2 = new javax.swing.JCheckBox();
        JC3 = new javax.swing.JCheckBox();
        JT1 = new javax.swing.JTextField();
        JCB1 = new javax.swing.JComboBox<>();
        JS1 = new javax.swing.JSpinner();
        JR4 = new javax.swing.JRadioButton();
        JR5 = new javax.swing.JRadioButton();
        JR6 = new javax.swing.JRadioButton();
        JC4 = new javax.swing.JCheckBox();
        JC5 = new javax.swing.JCheckBox();
        JC6 = new javax.swing.JCheckBox();
        JT2 = new javax.swing.JTextField();
        JCB2 = new javax.swing.JComboBox<>();
        JS2 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(JR1);
        JR1.setSelected(true);
        JR1.setText("Opcion 1");
        JR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JR1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(JR2);
        JR2.setText("Opcion 2");
        JR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JR2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(JR3);
        JR3.setText("Opcion 3");
        JR3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JR3ActionPerformed(evt);
            }
        });

        JC1.setText("Opcion 4");
        JC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JC1ActionPerformed(evt);
            }
        });

        JC2.setText("Opcion 5");
        JC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JC2ActionPerformed(evt);
            }
        });

        JC3.setText("Opcion 6");
        JC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JC3ActionPerformed(evt);
            }
        });

        JT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT1ActionPerformed(evt);
            }
        });
        JT1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JT1KeyPressed(evt);
            }
        });

        JCB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JCB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB1ActionPerformed(evt);
            }
        });

        JS1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                JS1StateChanged(evt);
            }
        });

        buttonGroup2.add(JR4);
        JR4.setText("Opcion 1");
        JR4.setEnabled(false);

        buttonGroup2.add(JR5);
        JR5.setText("Opcion 2");
        JR5.setEnabled(false);

        buttonGroup2.add(JR6);
        JR6.setText("Opcion 3");
        JR6.setEnabled(false);

        JC4.setText("Opcion 4");
        JC4.setEnabled(false);

        JC5.setText("Opcion 5");
        JC5.setEnabled(false);

        JC6.setText("Opcion 6");
        JC6.setEnabled(false);

        JT2.setEnabled(false);
        JT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT2ActionPerformed(evt);
            }
        });

        JCB2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JCB2.setEnabled(false);

        JS2.setEnabled(false);
        JS2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                JS2StateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JR3)
                    .addComponent(JR2)
                    .addComponent(JR1))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JC1)
                    .addComponent(JC2)
                    .addComponent(JC3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JT1)
                    .addComponent(JCB1, 0, 94, Short.MAX_VALUE)
                    .addComponent(JS1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JR4)
                    .addComponent(JR5)
                    .addComponent(JR6))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JC4)
                    .addComponent(JC5)
                    .addComponent(JC6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JS2)
                    .addComponent(JT2)
                    .addComponent(JCB2, 0, 94, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JR1)
                    .addComponent(JC1)
                    .addComponent(JT1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JR2)
                            .addComponent(JC2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JR3)
                            .addComponent(JC3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JCB1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JS1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JR4)
                    .addComponent(JC4)
                    .addComponent(JT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JR5)
                    .addComponent(JC5)
                    .addComponent(JCB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JR6)
                    .addComponent(JC6)
                    .addComponent(JS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JR1ActionPerformed
 if (evt.getSource() == JR1) {
            JR4.setSelected(JR1.isSelected());
            
 }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_JR1ActionPerformed

    private void JT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT1ActionPerformed
  
        
        
        
        
    }//GEN-LAST:event_JT1ActionPerformed

    private void JT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT2ActionPerformed

    private void JS2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_JS2StateChanged
    }//GEN-LAST:event_JS2StateChanged

    private void JS1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_JS1StateChanged
     if (evt.getSource() == JS1) {
            JS2.setValue(JS1.getValue());
        }
      
    }//GEN-LAST:event_JS1StateChanged

    private void JT1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JT1KeyPressed
 
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        if (evt.getSource() == JT1) {
            JT2.setText(JT1.getText());
          
        }
   }
    }//GEN-LAST:event_JT1KeyPressed

    private void JCB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB1ActionPerformed

if (evt.getSource() == JCB1) {
            JCB2.setSelectedItem(JCB1.getSelectedItem());
        }

       
    }//GEN-LAST:event_JCB1ActionPerformed
    private void JC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JC1ActionPerformed
 if (evt.getSource() == JC1) {
            JC4.setSelected(JC1.isSelected());
           
        }        // TODO add your handling code here:
    }//GEN-LAST:event_JC1ActionPerformed

    private void JC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JC2ActionPerformed
 if ( evt.getSource() == JC2 ) {          
            JC5.setSelected(JC2.isSelected());
        }
    }//GEN-LAST:event_JC2ActionPerformed

    private void JC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JC3ActionPerformed
 if ( evt.getSource() == JC3) {
          
            JC6.setSelected(JC3.isSelected());
        }        
    }//GEN-LAST:event_JC3ActionPerformed

    private void JR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JR2ActionPerformed
 if ( evt.getSource() == JR2 ) {
            JR5.setSelected(JR2.isSelected());   
 }
    }//GEN-LAST:event_JR2ActionPerformed

    private void JR3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JR3ActionPerformed
 if ( evt.getSource() == JR3) {
            JR6.setSelected(JR3.isSelected());  
 }// TODO add your handling code here:
    }//GEN-LAST:event_JR3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vimitador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vimitador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vimitador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vimitador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vimitador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox JC1;
    private javax.swing.JCheckBox JC2;
    private javax.swing.JCheckBox JC3;
    private javax.swing.JCheckBox JC4;
    private javax.swing.JCheckBox JC5;
    private javax.swing.JCheckBox JC6;
    private javax.swing.JComboBox<String> JCB1;
    private javax.swing.JComboBox<String> JCB2;
    private javax.swing.JRadioButton JR1;
    private javax.swing.JRadioButton JR2;
    private javax.swing.JRadioButton JR3;
    private javax.swing.JRadioButton JR4;
    private javax.swing.JRadioButton JR5;
    private javax.swing.JRadioButton JR6;
    private javax.swing.JSpinner JS1;
    private javax.swing.JSpinner JS2;
    private javax.swing.JTextField JT1;
    private javax.swing.JTextField JT2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
