package minicad;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Point;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LaboratorioU005_11
 */
public class MiniCAD extends javax.swing.JFrame {

    public final int ESPERANDO_PRIMER_PUNTO  = 0;
    public final int ESPERANDO_SEGUNDO_PUNTO = 1;
    public final int ESPERANDO_TERCER_PUNTO = 2;
    
    public final int LINEA     = 1;
    public final int TRIANGULO = 2;
    public final int CUADRADO  = 3;
    public final int CIRCULO   = 4;
    public final int OVALO     = 5;
    public final int TEXTO     = 6;

    Point punto1;
    Point punto2;
    Point punto3;
    
    ArrayList<Figura> aFiguras = new ArrayList<Figura>();
    
    int estado  = ESPERANDO_PRIMER_PUNTO;
    int figura  = LINEA;
    
    Color color = Color.BLACK;
    
    /**
     * Creates new form MiniCAD
     */
    public MiniCAD() {
        initComponents();
        this.punto1 = new Point();
        this.punto2 = new Point();
        this.punto3 = new Point();
        
        this.tfColor.setBackground(color);
    }
    
    void dibujarPunto(Point p, Color color){
        Graphics2D g2d = (Graphics2D) this.jPanel3.getGraphics();
        
        g2d.setColor(color);
        g2d.drawLine(p.x,p.y,p.x,p.y);
    }

    
    private void agregarLinea(Linea linea) {
        this.aFiguras.add(linea);
        Graphics2D g2d = (Graphics2D) this.jPanel3.getGraphics();
        linea.dibujar(g2d);
    }
    
    private void agregarTriangulo(Point punto1, Point punto2, Point punto3, Color color) {
        Linea l1, l2, l3;
        l1 = new Linea(punto1,punto2,color);
        l2 = new Linea(punto2,punto3,color);
        l3 = new Linea(punto3,punto1,color);
        
        Triangulo triangulo = new Triangulo(l1,l2,l3,color);
                
        this.aFiguras.add(triangulo);
        
        Graphics2D g2d = (Graphics2D) this.jPanel3.getGraphics();
        
        triangulo.dibujar(g2d);
        
        System.out.println("Se agrego triangulo");
        
    }
    
    private void agregarCuadrado(Cuadrado cuadrado) {
        this.aFiguras.add(cuadrado);
        Graphics2D g2d = (Graphics2D) this.jPanel3.getGraphics();
        cuadrado.dibujar(g2d);
    }

    private void agregarCirculo(Circulo circulo) {
        this.aFiguras.add(circulo);
        Graphics2D g2d = (Graphics2D) this.jPanel3.getGraphics();
        circulo.dibujar(g2d);
    }    
    
    private void agregarOvalo(Ovalo ovalo) {
        this.aFiguras.add(ovalo);
        Graphics2D g2d = (Graphics2D) this.jPanel3.getGraphics();
        ovalo.dibujar(g2d);
    }    
    
    void redibujar(){
        Graphics2D g2d = (Graphics2D) this.jPanel3.getGraphics();
        
        Iterator itr = aFiguras.iterator();
        int i = 0;
        while(itr.hasNext()){
            Figura f = (Figura)itr.next();
            
            if (f instanceof Linea){
                Linea l = (Linea)f;
                l.dibujar(g2d);
            }
            
            if (f instanceof Triangulo){
                Triangulo t = (Triangulo)f;
                t.dibujar(g2d);
            }                       
        }   
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        tfColor = new javax.swing.JTextField();
        jToggleButton6 = new javax.swing.JToggleButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(479, 50));

        jButton1.setText("Borrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 395, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnGuardar))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        buttonGroup1.add(jToggleButton1);
        jToggleButton1.setSelected(true);
        jToggleButton1.setText("Linea");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton2);
        jToggleButton2.setText("Triangulo");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton3);
        jToggleButton3.setText("Rectangulo");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton4);
        jToggleButton4.setText("Circulo");
        jToggleButton4.setAlignmentY(0.0F);
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton5);
        jToggleButton5.setText("Ovalo");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        tfColor.setEditable(false);
        tfColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfColorMouseClicked(evt);
            }
        });

        buttonGroup1.add(jToggleButton6);
        jToggleButton6.setText("Texto");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToggleButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToggleButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToggleButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfColor))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextField1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(tfColor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jPanel3ComponentResized(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        int x = evt.getX();
        int y = evt.getY();
        
        switch (figura){
            case LINEA:
                if (estado == this.ESPERANDO_PRIMER_PUNTO){
                    this.punto1.x = x;
                    this.punto1.y = y;
                    punto2.x = punto1.x+1;
                    punto2.y = punto1.y+1;
                    this.dibujarPunto(punto1,this.color);

                    estado = this.ESPERANDO_SEGUNDO_PUNTO;
                } else {
                    this.punto2.x = x;
                    this.punto2.y = y;
                    agregarLinea(new Linea(this.punto1, this.punto2,this.color));
                    estado = this.ESPERANDO_PRIMER_PUNTO;
                }
                break;
                
            case TRIANGULO:
                if (estado == this.ESPERANDO_PRIMER_PUNTO){
                    this.punto1.x = x;
                    this.punto1.y = y;
                    punto2.x = punto1.x+1;
                    punto2.y = punto1.y+1;
                    System.out.println("Se agrego primer punto");
                    estado = this.ESPERANDO_SEGUNDO_PUNTO;
                } else if (estado == this.ESPERANDO_SEGUNDO_PUNTO){
                    this.punto2.x = x;
                    this.punto2.y = y;
                    System.out.println("Se agrego segundo punto");
                    estado = this.ESPERANDO_TERCER_PUNTO;                    
                    
                } else if (estado == this.ESPERANDO_TERCER_PUNTO) {
                    this.punto3.x = x;
                    this.punto3.y = y;
                    agregarTriangulo(this.punto1, this.punto2,punto3,this.color);
                    estado = this.ESPERANDO_PRIMER_PUNTO;
                    System.out.println("Se agrego tercer punto");
                }
                break;                                
            case CUADRADO:
                if (estado == this.ESPERANDO_PRIMER_PUNTO){
                    this.punto1.x = x;
                    this.punto1.y = y;
                    punto2.x = punto1.x+1;
                    punto2.y = punto1.y+1;
                    this.dibujarPunto(punto1,this.color);

                    estado = this.ESPERANDO_SEGUNDO_PUNTO;
                } else {
                    this.punto2.x = x;
                    this.punto2.y = y;
                    agregarCuadrado(new Cuadrado(this.punto1,this.punto2,this.color));
                    estado = this.ESPERANDO_PRIMER_PUNTO;
                }
                break;
            case CIRCULO:
                if (estado == this.ESPERANDO_PRIMER_PUNTO){                    
                    this.punto1.x = x;
                    this.punto1.y = y;
                    punto2.x = punto1.x+1;
                    punto2.y = punto1.y+1;
                    System.out.println("Se dibuja punto");

                    estado = this.ESPERANDO_SEGUNDO_PUNTO;
                } else {
                    this.punto2.x = x;
                    this.punto2.y = y;
                    System.out.println("Se agrega el circulo");
                    agregarCirculo(new Circulo(this.punto1, Math.abs(this.punto2.x-this.punto1.x),this.color));
                    estado = this.ESPERANDO_PRIMER_PUNTO;
                }
                break;
            case OVALO:
                if (estado == this.ESPERANDO_PRIMER_PUNTO){                    
                    this.punto1.x = x;
                    this.punto1.y = y;
                    punto2.x = punto1.x+1;
                    punto2.y = punto1.y+1;
                    System.out.println("Se dibuja punto");

                    estado = this.ESPERANDO_SEGUNDO_PUNTO;
                } else {
                    this.punto2.x = x;
                    this.punto2.y = y;
                    System.out.println("Se agrega el circulo");
                    agregarOvalo(new Ovalo(this.punto1, this.punto2,this.color));
                    estado = this.ESPERANDO_PRIMER_PUNTO;
                }
                break;
            case TEXTO:
                if (estado == this.ESPERANDO_PRIMER_PUNTO){                    
                    this.punto1.x = x;
                    this.punto1.y = y;
                    punto2.x = punto1.x+1;
                    punto2.y = punto1.y+1;
                    System.out.println("Se dibuja punto");
                    
                    Graphics2D g2d = (Graphics2D) this.jPanel3.getGraphics();
                    
                    g2d.drawString(this.jTextField1.getText(), this.punto1.x, this.punto1.y);

                    estado = this.ESPERANDO_PRIMER_PUNTO;
                }
                break;                 
        }        
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.jPanel3.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfColorMouseClicked
        // TODO add your handling code here:
        Color newColor;
        newColor=JColorChooser.showDialog(this,"Seleccionar color",this.color); 
        
        if(newColor!=null){
            this.color = newColor;
        }
        
        this.tfColor.setBackground(this.color);
        
    }//GEN-LAST:event_tfColorMouseClicked

    private void jPanel3ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel3ComponentResized
        // TODO add your handling code here:
       // Iterator itr = alineas.iterator();
        redibujar();     
    }//GEN-LAST:event_jPanel3ComponentResized

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        redibujar();
    }//GEN-LAST:event_formWindowActivated

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        this.figura = LINEA;        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        this.figura = TRIANGULO;
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // L x1,y1,x2,y2,color
        // T x1,y1,x2,y2,x3,y3,color
        
        JFileChooser chooser = new JFileChooser();
        
        // FileNameExtensionFilter filter = new FileNameExtensionFilter(
        //    "Documentos", "doc", "docx", "dot");
        // chooser.setFileFilter(filter);
        String nombreArchivo="";
        int returnVal = chooser.showSaveDialog(this);
        
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            
           nombreArchivo = chooser.getSelectedFile().getPath();
           
            try {
                FileWriter fw = new FileWriter(nombreArchivo);
                
                Iterator itr = aFiguras.iterator();
                int i = 0;
                while(itr.hasNext()){
                    Figura f = (Figura)itr.next();

                    if (f instanceof Linea){
                        Linea l = (Linea)f;
                        String str = String.format("L,%d,%d,%d,%d,%s\n",l.punto1.x,l.punto1.y,l.punto2.x,l.punto2.y,Integer.toHexString(l.color.getRGB()).substring(2));
                        fw.write(str);
                    }

                    if (f instanceof Triangulo){
                        Triangulo t = (Triangulo)f;
                        String str = String.format("T,%d,%d,%d,%d,%d,%d,%s\n",t.linea1.punto1.x,t.linea1.punto1.y,t.linea1.punto2.x,t.linea1.punto2.y,t.linea2.punto2.x,t.linea2.punto2.y,Integer.toHexString(t.color.getRGB()).substring(2));
                        fw.write(str);
                    }
                    if (f instanceof Cuadrado){
                        Cuadrado c = (Cuadrado)f;                        
                        //fw.write(str);
                    }                      
                } 
                                                
                fw.close();
            } catch (IOException ex) {
                Logger.getLogger(MiniCAD.class.getName()).log(Level.SEVERE, null, ex);
            }           
           
        }                
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        this.figura = CUADRADO;// TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        this.figura = CIRCULO;
        System.out.println("Dibujo de CIRUCLO seleccionado");
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        // TODO add your handling code here:
        this.figura = OVALO;
        System.out.println("Dibujo de OVALO seleccionado");
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        // TODO add your handling code here:
        this.figura = TEXTO;
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiniCAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiniCAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiniCAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiniCAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiniCAD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JTextField tfColor;
    // End of variables declaration//GEN-END:variables

}
